### ISSUE TITLE
URL issues after ownership transfer

### ISSUE THREAD

**Issue by samadhi1311** [samadhi1311/overnight#1]
As the ownership changed, the URL of the repo has also changed. This has led to invalid URLs for assets including images, stylesheets, scripts, and GitHub pages URL.

To fix this issue,  I suggest the following modifications.

![image](https://github.com/Sithruby/overnight/assets/69573759/762860f1-e408-4e7f-8916-37535cbc46c5)
1. Change `--public-url` to `https://sithruby.github.io/overnight/` in the build script of package.json.
2. Change the author to `sithruby`
3. Also change the ReadMe and GitHub repo description reflecting the above-mentioned changes.

After completing modifications run the `npm build` command and then commit changes.

**Comment by samadhi1311** [comment]
Sithu, You haven't fixed the issue yet. You have to change the URL. Not to
delete the entire line. Can you read the PDF I sent you?
Then change the scripts first. Then build the website. Then commit it with
a message. Not just 'a'. Use something like 'Fixed URL issue'. Please?

**Comment by Sithruby** [comment]
I didn't delete i add.. can you check..

**Comment by samadhi1311** [comment]
Oh yes. You fixed the URL. Now you need to build the website. Open it with
VS Code and then run "npm build" command.

**Comment by samadhi1311** [comment]
Sithu,  can you close the pull request...?
